config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root 'pages#index'
  get 'subreddits/', to: 'subreddits#index'
  get 'subreddits/:subreddit', to: 'subreddits#show'
  get 'about', to: 'pages#about', as: 'about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :subreddit
  has_many :grammar_mistakes
  scope :todays_comments, -> { where( "commented_on >= ?", Time.zone.now.beginning_of_day) }
  scope :todays_errors, -> { todays_comments.where("reply_status != 'never'") }
  scope :todays_graph_data, -> { todays_errors.joins(:subreddit).group(:name).count }
  scope :next_reply, -> { where(reply_status: "soon").first }
  scope :before_today, -> { where( "commented_on < ?", Time.zone.now.beginning_of_day) }
  scope :no_your_mistakes, -> { where( "reply_status = 'never'" ) }
  scope :your_mistakes, -> { where( "reply_status != 'never'" ) }
  
  def commented
    self.update(reply_status: 'commented')
  end
end 

app/models/comments_by_day.rb
class CommentsByDay < ActiveRecord::Base
  belongs_to :subreddit
  validates :day, :uniqueness => {:scope => [:mistake]}
end 

app/models/grammar_mistake.rb
class GrammarMistake < ActiveRecord::Base
  belongs_to :comment
end 

app/models/subreddit.rb
class Subreddit < ActiveRecord::Base
  has_many :comments
  has_many :comments_by_days

  def todays_comments
    self.comments.todays_comments
  end

  def todays_errors
    self.todays_comments.todays_errors
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :todays_graph_data,:current_subreddits

  def current_subreddits
    @subreddits = Subreddit.where(name: @todays_graph_data.keys)
  end

  def todays_graph_data
    @todays_graph_data = Comment.todays_graph_data
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about  
  end

end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController

  def index
    @todays_graph_data = Comment.todays_graph_data
    @subreddits = Subreddit.where(name: @todays_graph_data.keys)
    @todays_percentage_graph_data = Hash.new
    
    @subreddits.each do |subreddit|
      total_today = subreddit.todays_comments.count
      @todays_percentage_graph_data[subreddit.name] = (@todays_graph_data[subreddit.name] / total_today.to_f) * 100
    end
  end

  def show
    @subreddit = Subreddit.find_by_name(params[:subreddit])
    @comments = @subreddit.todays_comments
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
    <link href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Homemade+Apple' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="fixed">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1 class='homemade'><%= link_to "YourWrongBot", "http://www.yourwrongbot.com" %></h1>
          </li>
           <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
          <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">

            <li><%= link_to "Hire Me", "https://www.linkedin.com/in/joweisner" %></li>
            <li><%= link_to "Bot on Reddit", "http://www.reddit.com/user/YourWrongBot/" %></li>
            <li class="has-dropdown">
              <%= link_to "Subreddits", subreddits_path %>
              <ul class="dropdown">
                <% @subreddits.each do |subreddit| %>
                  <li><%= link_to subreddit.name, "/subreddits/"+subreddit.name %></li>
                <% end %>
              </ul>
            </li>
          </ul>

          <!-- Left Nav Section -->
          <ul class="left">
            <li><%= link_to "Today's Statistics", subreddits_path  %></li>
          </ul>
        </section>
      </nav>
    </div>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="row">
  <div class="span4">
    <h3>Why bother?</h3>
    <p>Because when I was much younger I was a bit of a grammar nazi while online. I felt like I was helping each time I corrected someone and so I corrected people a lot. It was hard to come to grips with the fact that most people felt insulted while being corrected but I justified the action by thinking about when the next time the person wrote the same thing they would think about the right way to do it. I was doing people a favor even if they could not recognize it at that exact moment.</p>
    <p>I don't correct people's grammar any more, the backlash from friends is not worth it, but my bot does.</p>
  </div>

  <div class="span4">
    <h3>How does it all work?</h3>
    <p>The for programmers the code is all open source right <%= link_to "here.", "https://github.com/JohnathanWeisner/YourWrongBot-rails" %></p>
    <p>For everyone else, four times a day the bot asks Reddit for all of the comments from the top posts in the pre-chosen subreddits (A bit more complex, but not all that much more). Then the bot selects the comments containing the words "your", "you're", and "you are". Once those comments are found they are sent to a grammar correcting api (an interface for another program). When we get the grammar checked out, we check and see if the corrections include a change from one type of "your" to another type of "you're". All of the comments containing "your", "you're", and "you are" get stored in a database and the comments with "your" errors get a special tag that lets another process know that they need a reply.</p>
    <p>The reply process runs every ten minutes and searches the database for comments that need replies.</p>
    <p>Simple, right?</p>
  </div>
</div>

<div class="row">
  <div class="span4">
    <h3>No but seriously, why bother?</h3>
    <p>I wanted practice setting up autonomous tasks and building an application.</p>
  </div>

  <div class="span4">
    <h3>Who are you?</h3>
    <p><%= link_to "Johnathan Weisner","https://github.com/johnathanweisner" %></p>
  </div>
</div>

<div class="row">
  <div class="span8">
    <h3>Originally a Group Project</h3>
    <p>
      This was originally started as a group project by Keaty Irene, Brendan Joe, Adam Godel, Christine Feaster, and Johnathan Weisner. I asked if I could continue working on the project and I rewrote all of the code.
    </p>
  </div>
</div>

app/views/pages/home.html.erb
<h1> Your Wrong Bot </h1>

app/views/pages/index.html.erb
<section id="homepage-hero">
    <div class="row">
      <div id="hero-text" class="small-12 medium-6 columns end right">
        <h3>"Holy shit, I don't know how to feel about this. On one hand the bot is totally right. On the other hand, well, it's just kind of a dick."</h3>
        <h4 class="text-right">-/u/Darkurai</h4>
      </div>
    </div>
</section>

<section id="about">
  <div class="row text-center">
    <div class="small-12 centered-text">
      <h3>Grammar Correcting Reddit Bot</h3>
      <p>The bot that fixes "your", "you're", and "you are" usage on Reddit.</p>
    </div>
  </div>
</section>
  
<section id="how-it-works">
  <div class="row text-center">
    <div class="small-12 column">
      <h2>How does it all work?</h2>
    </div>
  </div>

  <div class="row text-center">
    <div class="small-12 medium-4 column">
      <h4>Four times a day</h4> 
        <p>The bot asks Reddit for all of the comments from the top posts in the top subreddits that the bot is not already banned from (not everyone likes him).</p>
    </div>
    <div class="small-12 medium-4 column">
      <h4>"Your" Comments Selected </h4>
      <p>Then the bot selects the comments containing the words "your", "you're", and "you are" and sends them out to a separate API to check for grammar mistakes.</p> 
    </div>

    <div class="small-12 medium-4 column">
      <h4>Mistakes</h4>
      <p>Once the comments come back from getting checked out the comments with "your" mistakes get commented on every 10 minutes.</p>
    </div>
  </div>

  <div class="row text-center">
    <div class="medium-10 medium-offset-1 columns centered-text">
        <h2>Simple, right?</h2>
    </div>
  </div>
</section>

app/views/subreddits/index.html.erb
<section id="subreddits">
<%= 
  column_chart @todays_percentage_graph_data, 
  id: "Mistaken 'Your', 'You're', or 'You are' percentage", 
  library: {title: "Today's Statistics", hAxis: {title: "Subreddits"}, 
    vAxis: {title: "Percent Wrong"}}
%>

<%= 
  column_chart @todays_graph_data, 
  id: "Mistaken 'Your', 'You're', or 'You are' count", 
  library: {hAxis: {title: "Subreddits"}, vAxis: {title: "Total Wrong"}}
%>
</section>

app/views/subreddits/show.html.erb
<section id="sub-statistics">
  <div class="row text-center">
    <div class="medium-11 medium-offset-1 column end">
      <h2>/r/<%= @subreddit.name %></h2>
      <h5>Today's comments containing "your", "you're", or "you are"</h5>
      <p><span class="success label">Total comments:</span> <%=@comments.count%><br>
      <span class="alert label">Total errors:</span> <%=@comments.todays_errors.count%></p>

  <% if @comments %>
      <h5>Corrections done</h5>
    </div>
    <% @comments.todays_errors.each_slice(3) do |first_comment,second_comment, third_comment| %>
      <div class="row text-center">
        <div class="small-12 medium-4 column">
          <span class="alert label">from</span>
          <p><%=first_comment.body%></p>
          <span class="success label">to</span>
          <p><%=first_comment.retort%></p>
        </div>
        <% if second_comment %>
          <div class="small-12 medium-4 column">
            <span class="alert label">from</span>
            <p><%=second_comment.body%></p>
            <span class="success label">to</span>
            <p><%=second_comment.retort%></p>
          </div>
        <% end %>
        <% if third_comment %>
          <div class="small-12 medium-4 column">
            <span class="alert label">from</span>
            <p><%=third_comment.body%></p>
            <span class="success label">to</span>
            <p><%=third_comment.retort%></p>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</section>